### ISSUE TITLE
WithFormParam?

### ISSUE THREAD

**Issue by montehansen** [sketch7/FluentlyHttpClient#19]
I don't see any support for form parameters, and such. I see support for query parameters though. Am I missing that somewhere? Other than that, I love the builder interface.

**Comment by claylaut** [comment]
hey @montehansen,
To add querystring parameters you need to use `.WithQueryParams`
If you want to add body content you need to use: `.WithBody`

Hope I've answered your question :)
Thanks for using FluentlyHttpClient, don't forget to star the project.

**Comment by stephenlautier** [comment]
@montehansen did that solve your issue?

**Comment by anicething** [comment]
hi, how to upload file with this libary?

**Comment by montehansen** [comment]
Yes, it does. Thanks for writing this library, don't know why there weren't 10 just like it =). I look forwad to using it in my mobile app. ANICETHING has a good question about files too, Also, has it been tested on mono?

**Comment by stephenlautier** [comment]
@montehansen glad you like it!

Re-upload he opened a new issue, its supported via the raw httpclient (or perhaps by using with body) but its not nicely supported with fluently, I will try to implement a nicer way to do this.

Unfortunately, I don't test this on Mono so I'm not entirely sure, the target is mainly .NET Standard
