### ISSUE TITLE
hi, how to upload file with this libary?

### ISSUE THREAD

**Issue by anicething** [sketch7/FluentlyHttpClient#20]

**Comment by stephenlautier** [comment]
Currently, it doesn't have directly support for it, I will create an issue and try to get it implemented.

In the mean time you can use directly the RawClient in order to do this, but as I said I will try to get an easier way to handle file upload, thanks

**Comment by stephenlautier** [comment]
@anicething Its been quite a while, but I implemented file uploading simplified apis, see example: https://github.com/sketch7/FluentlyHttpClient#file-upload
or refer to unit tests for more https://github.com/sketch7/FluentlyHttpClient/blob/master/test/Integration/FileUploadIntegrationTest.cs

its available on an unstable build `3.9.0-dev474`, will publish as stable in few days

**Comment by stephenlautier** [comment]
This was released some months ago, so I will close it.
