### ISSUE TITLE
How do I configure Proxy?

### ISSUE THREAD

**Issue by RenanDelacroix** [sketch7/FluentlyHttpClient#54]
Hi, I need to configure a proxy on the request. But I can't find any information of how do I do that.
Can you Help me?
How can I set my Proxy configuration in FluentlyHttpClient.

**Comment by stephenlautier** [comment]
How would configure the proxy in the traditional `HttpClient`?  Are you referring to the `MessageHandler`?

**Comment by RenanDelacroix** [comment]
I'm referring to the proxy credentials.
If I would configure at traditional client it would be like at the end of the message.
I wanted to know how can I set credentials and set that by using Fluently.

//Example of traditional Client:
var proxy = new WebProxy
{
    Address = new Uri($"http://{proxyHost}:{proxyPort}"),
    BypassOnLocal = false,
    UseDefaultCredentials = false,

    // *** These creds are given to the proxy server, not the web server ***
    Credentials = new NetworkCredential(
        userName: proxyUserName,
        password: proxyPassword)
};

// Now create a client handler which uses that proxy
var httpClientHandler = new HttpClientHandler
{
    Proxy = proxy,
};

// Omit this part if you don't need to authenticate with the web server:
if (needServerAuthentication)
{
    httpClientHandler.PreAuthenticate = true;
    httpClientHandler.UseDefaultCredentials = false;

    // *** These creds are given to the web server, not the proxy server ***
    httpClientHandler.Credentials = new NetworkCredential(
        userName: serverUserName,
        password: serverPassword);
}

// Finally, create the HTTP client object
var client = new HttpClient(handler: httpClientHandler, disposeHandler: true);

**Comment by stephenlautier** [comment]
Ah yea for the MessageHandler as i suspected 

Quite simple 

```cs
fluentHttpClientBuilder.WithMessageHandler(httpClientHandler)
```

**Comment by RenanDelacroix** [comment]
Hi!
I thank you... 
But, i just did as you said and it doesn't work, I can't reach the endpoint.
I tested in orginal httpClient and worked fine. When I try to use Fluently it just respond some erros...
When I try to see the Result I got Exception.

Follows the message:


![image](https://user-images.githubusercontent.com/13875453/66592526-97a96580-eb6b-11e9-8e43-c4302440166c.png)

**Comment by RenanDelacroix** [comment]
And that's the exception:
 
"detail": "One or more errors occurred. (Response status code does not indicate success: 404 ().)",
    "innerException": "Response status code does not indicate success: 404 ().",
    "innerExceptionInnerExpetion": "",
    "targetSite": "GetResultCore"

**Comment by RenanDelacroix** [comment]
Oh, and this link returns 404:
https://github.com/sketch7/FluentlyHttpClient/blob/feature/timer-mw-debuglog/test/LoggingHttpMiddlewareTest.cs#L29

**Comment by stephenlautier** [comment]
Opps sorry.. by mistake i linked from a branch - updated https://github.com/sketch7/FluentlyHttpClient/blob/master/test/LoggingHttpMiddlewareTest.cs#L29

Strange, it should work - theres not much adding to it from my end when setting the `HttpMessageHandler`

If you can either provide me a working example which I can check or at least send me how you're configuring fluently with the message handler maybe I can help
