### ISSUE TITLE
Allow IServiceCollection independent IoC container registration

### ISSUE THREAD

**Issue by Kayes-Islam** [sketch7/FluentlyHttpClient#70]
Use Case:
I was trying to use it on .net core project with MvvmCross which has an IoC provider that does not implement IServiceCollection. So I did not find any easy way to use this library in my .net core project.

**Comment by stephenlautier** [comment]
Unfortunately, I'm not familiar with that. However seems a bit odd that these days it doesn't support `IServiceCollection`, as most of the libraries won't work. 

It somehow needs to be hooked to the IoC as it uses `IServiceProvider` internally.

This is more a IoC issue so not much I can do. 

- Look into replacing IoC container for MvvmCross (best option)
- Somehow IoC implements the Microsoft DI abstraction
- Create another container which supports Microsoft DI abstraction and maybe hook it to your DI (ala service locator when registering)

**Comment by Kayes-Islam** [comment]
@stephenlautier Thanks for the reply. Yes you are right. An error on my side is that when I misread the documentation and thought IServiceCollection is asp.net core specific, those extension methods listed confused me a bit.

I agree with all the options you provided and will be implementing the option 2 in my case. Closing this issue.
